version: 1
formatters:
    default:
        format: "%(asctime)s - %(levelname)8s - %(funcName)15.15s:%(lineno)-4d - %(process)6d / %(processName)8s - %(message)s"

handlers:
    console:
        formatter: default
        class: logging.StreamHandler
    logfile:
        formatter: default
        class: logging.handlers.RotatingFileHandler
        filename: logs/logging.log
        maxBytes: 10240000
        backupCount: 3
    verifier:
        formatter: default
        class: logging.handlers.RotatingFileHandler
        filename: logs/verifier.log
        maxBytes: 10240000
        backupCount: 3

loggers:
    '':
        handlers: [console, logfile]
        level: INFO
    'verifier':
        handlers: [verifier]
        level: INFO
        propagate: 0
